MxShop/urls.py
"""MxShop URL Configuration"""

from django.conf.urls import url, include
from django.views.static import serve

import xadmin
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token
from MxShop.settings import MEDIA_ROOT
# from goods.views_base import GoodsListView
from goods.views import GoodsListView, GoodsViewSet, CategoryViewSet, BannerViewSet,\
    IndexCategoryViewSet
from user_operation.views import UserFavViewSet, UserLeavingMessageViewSet, AddressViewSet
from users.views import SmsCodeViewSet, UserViewSet
from trade.views import ShoppingCartViewSet, OrderInfoViewSet
from musics.views import MusicViewSet

# =================================================================================
# Create a router and register our viewsets with it.
root_router = DefaultRouter()

# category的url
root_router.register(r'categorys', CategoryViewSet, base_name='categorys')
# 商品的url
root_router.register(r'goods', GoodsViewSet, base_name='goods')
# 用户收藏的url
root_router.register(r'userfavs', UserFavViewSet, base_name='userfavs')
# banner 的url
root_router.register(r'banners', BannerViewSet, base_name='banners')
# 首页商品系列数据 的url
root_router.register(r'indexcategorys', IndexCategoryViewSet, base_name='indexcategorys')
# code
root_router.register(r'code', SmsCodeViewSet, base_name='code')
# user注册
root_router.register(r'users', UserViewSet, base_name='users')
# 用户留言功能
root_router.register(r'messages', UserLeavingMessageViewSet, base_name='messages')
# 收货地址
root_router.register(r'address', AddressViewSet, base_name='address')
# 购物车
root_router.register(r'shopcarts', ShoppingCartViewSet, base_name='shopcarts')
# 订单
root_router.register(r'orders', OrderInfoViewSet, base_name='orders')





# ============================================= learn，使用as_view绑定http的行为和函数=#
goods_list = GoodsViewSet.as_view({
    'get': 'list',
})
# =================================================================================
from users.api_root import api_root
urlpatterns = [
    url(r'^', include(root_router.urls, namespace='goods')),
    # 管理后台url
    url(r'^xadmin/', xadmin.site.urls),
    # 图片访问url
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # 商品列表页
    url(r'goods/$', goods_list, name='viewset_demo'),
    # drf 项目接口文档
    url(r'docs/', include_docs_urls(title='muxueshegnxian')),
    # drf 登录授权窗口
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # 这个是 rest framework jwt 认证的模式
    url(r'^login/', obtain_jwt_token),
    # snippet
    url(r'^api/', include('snippet.urls', namespace='snippet')),
    # user
    url(r'^api/', include('users.urls', namespace='user')),
    # musics ,相关的view_set都注册到那儿
    url(r'^api/', include('musics.urls', namespace='musics')),
    # posts ,
    url(r'^api/', include('posts.urls', namespace='posts')),
    # api_root
    url(r'^api-root/', api_root),
    # 验证DRF对嵌套post的支持
    # url(r'^blogpost/', include('learn_blogposts.urls', namespace='learn_blogposts'))
    # 验证drf对嵌套post支持
    #url(r'^postapi', include('api.urls',namespace='postapi')),
]

apps/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import HandleExcelView
urlpatterns = [
    # 商品列表页
    url(r'xls/$', HandleExcelView.as_view(), name='handle_excel'),
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

extra_apps/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

import django
from django.conf.urls import url
from django.contrib.auth import views

if django.VERSION < (1, 11):
    login = views.login
    login_kwargs = {'template_name': 'rest_framework/login.html'}
    logout = views.logout
else:
    login = views.LoginView.as_view(template_name='rest_framework/login.html')
    login_kwargs = {}
    logout = views.LogoutView.as_view()


app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', login, login_kwargs, name='login'),
    url(r'^logout/$', logout, name='logout'),
]

templates/upload_xls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form action="{% url 'user:handle_excel' %} " method="post" enctype="multipart/form-data">
        <input name="images" type="file" id="upfile" />
        <img src="dfa/.jpg" alt="上传照片" title="">
        <p>上传文件,并上传需要读取的表</p>
        <input type="submit" value="提交">
        {% csrf_token %}
    </form>

    <input type="file" id="upfile" />
    <input type="button" onclick="readThis();" value="读取">
    <br>
    <textarea id="txtArea" cols=50 rows=10></textarea>

    <script>
        function readThis(){
            var tempStr = "";
            var filePath= document.all.upfile.value;
            var oXL = new ActiveXObject("Excel.application");
            var oWB = oXL.Workbooks.open(filePath);
            oWB.worksheets(1).select();
            var oSheet = oWB.ActiveSheet;
            try{
            for(var i=2;i<46;i++){
                if(oSheet.Cells(i,2).value =="null" || oSheet.Cells(i,3).value =="null" )
                break;
                var a = oSheet.Cells(i,2).value.toString()=="undefined"?"":oSheet.Cells(i,2).value;
                tempStr+=(" "+oSheet.Cells(i,2).value+
                " "+oSheet.Cells(i,3).value+
                " "+oSheet.Cells(i,4).value+
                " "+oSheet.Cells(i,5).value+
                " "+oSheet.Cells(i,6).value+"\n");
            }
        }catch(e){
        //alert(e);
        document.all.txtArea.value = tempStr;
        }
        document.all.txtArea.value = tempStr;
        oXL.Quit();
        CollectGarbage();
        }
    </script>
</body>

</html>